#!/usr/bin/env bash

if [[ "$1" = '-v' || "$1" = '--version' ]]; then
  jq -r .version ~/.config/crew-mates/package.json
  exit 0
fi

RUNTIME_PATH=${RUNTIME_PATH:-"/project-cargo"}

cd $RUNTIME_PATH

LOG_MESSAGE=""

log () {
  echo $LOG_MESSAGE

  if [ -f "$RUNTIME_PATH/comms.sh" ]; then
    $RUNTIME_PATH/comms.sh "$LOG_MESSAGE"
  fi
}

TRIES=0

OUTPUT_FILE=""

LOG_MESSAGE="💾 Consolidating $PKG_NAME v$PROJECT_CARGO_VERSION..."
log

LOG_MESSAGE=">>> Stage: $STAGE"
log

pack () {
  DEPLOYED_VERSION=$(hostler get $PKG_REPO_URL/$PKG_NAME/$STAGE.project-cargo.version)

  if [ "$PROJECT_CARGO_VERSION" = "$DEPLOYED_VERSION" ]; then
    LOG_MESSAGE="🚨 ERROR: Project cargo version for $PKG_NAME is the same as version deployed. Bump the project cargo version and try again."
    log
    exit 1
  fi

  LOG_MESSAGE="Packing project cargo for $PKG_NAME: v$PROJECT_CARGO_VERSION"
  log

  OUTPUT_FILE=project-cargo-$PROJECT_CARGO_VERSION.tgz

  echo $PROJECT_CARGO_VERSION > project-cargo.version &&\
  tar --exclude=$OUTPUT_FILE --exclude=$STAGE.project-cargo.version --exclude=$OUTPUT_FILE.checksum -czf $OUTPUT_FILE $(ls -d ./* ./.??* 2>/dev/null) &&\
  echo $PROJECT_CARGO_VERSION > $STAGE.project-cargo.version &&\
  md5sum $OUTPUT_FILE > $OUTPUT_FILE.checksum
}

upload () {
  hostler put $PKG_REPO_URL/$PKG_NAME/$OUTPUT_FILE $OUTPUT_FILE &&\
  hostler put $PKG_REPO_URL/$PKG_NAME/$OUTPUT_FILE.checksum $OUTPUT_FILE.checksum &&\
  hostler put $PKG_REPO_URL/$PKG_NAME/$STAGE.project-cargo.version $STAGE.project-cargo.version
}

cleanup () {
  rm -f project-cargo.version
  rm -f project-cargo-$PROJECT_CARGO_VERSION.tgz
  rm -f $STAGE.project-cargo.version
  rm -f project-cargo-$PROJECT_CARGO_VERSION.tgz.checksum
}

attempt () {
  ((TRIES=TRIES+1))
  LOG_MESSAGE=">>> Pack attempt: $TRIES"
  log

  if [ "$TRIES" -le 3 ]; then
    { pack && upload; } || { cleanup && attempt; }
    RESULT=$?
    cleanup
    return $RESULT
  else
    LOG_MESSAGE="🚨 FAILED PACKING PROJECT CARGO AFTER $TRIES ATTEMPTS!"
    log
    cleanup
    return 1
  fi
}

attempt && LOG_MESSAGE="📦 Packed and uploaded project cargo after $TRIES tries" log
